### ISSUE TITLE
Error while running backand sync --app appName --folder ./public AccessDenied:

### ISSUE THREAD

**Issue by waqas19921** [backand/backand-cli#1]
I am running 
backand sync --app appName --folder ./public

and getting this error

> AccessDenied: Access Denied
>     at Request.extractError (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/services/s3.js:577:35)
>     at Request.callListeners (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>     at Request.emit (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/request.js:683:14)
>     at Request.transition (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/request.js:38:9)
>     at Request.<anonymous> (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/request.js:685:12)
>     at Request.callListeners (/usr/local/lib/node_modules/backand/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

**Comment by waqas19921** [comment]
@evilstickman @kornatzky @relly @itayher @yarivat
